-- Oracle
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM (SELECT *
     FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE 'Intact%') i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID AND o.SEX_UPON_OUTCOME NOT LIKE 'Intact%';
-- MySQL
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM ANIMAL_INS i LEFT JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.SEX_UPON_INTAKE LIKE "%Intact%" AND o.SEX_UPON_OUTCOME NOT LIKE "%Intact%"
ORDER BY ANIMAL_ID;