SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME
FROM (SELECT *
     FROM ANIMAL_INS
     WHERE SEX_UPON_INTAKE LIKE 'Intact%') i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID AND o.SEX_UPON_OUTCOME NOT LIKE 'Intact%';