-- Oracle
SELECT i.NAME, i.DATETIME
FROM (SELECT *
      FROM ANIMAL_INS
      ORDER BY DATETIME) i, ANIMAL_OUTS o
WHERE i.ANIMAL_ID = o.ANIMAL_ID(+) AND o.DATETIME IS NULL AND ROWNUM <= 3;
-- MySQL
SELECT i.NAME, i.DATETIME
FROM ANIMAL_INS i LEFT JOIN ANIMAL_OUTS o
ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE o.ANIMAL_ID iS NULL
ORDER BY i.DATETIME
LIMIT 3;
-- KB 준비 SQL 연습
SELECT i.NAME, i.DATETIME
FROM ANIMAL_INS i
LEFT JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE o.ANIMAL_ID IS NULL
ORDER BY i.DATETIME
LIMIT 3;