-- Oracle
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_OUTS o
LEFT OUTER JOIN ANIMAL_INS i
ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE i.ANIMAL_ID IS NULL
ORDER BY o.ANIMAL_ID, o.NAME;
-- MySQL
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_OUTS o LEFT JOIN ANIMAL_INS i
ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE i.ANIMAL_ID IS NULL
ORDER BY o.ANIMAL_ID;
-- KB 준비 SQL 연습
SELECT o.ANIMAL_ID, o.NAME
FROM ANIMAL_INS i
RIGHT OUTER JOIN ANIMAL_OUTS o ON i.ANIMAL_ID = o.ANIMAL_ID
WHERE i.ANIMAL_ID IS NULL
ORDER BY o.ANIMAL_ID;