-- Oracle
-- Case 1:
SELECT DATETIME
FROM (SELECT *
     FROM ANIMAL_INS
     ORDER BY DATETIME DESC)
WHERE ROWNUM = 1;
-- -- Case 2:
-- SELECT MAX(DATETIME)
-- FROM ANIMAL_INS;

-- MySQL
-- Case 1:
SELECT MAX(DATETIME)
FROM ANIMAL_INS;

-- -- Case 2:
-- SELECT DATETIME
-- FROM ANIMAL_INS
-- ORDER BY DATETIME DESC
-- LIMIT 1;