-- Oracle
-- Case 1:
SELECT DATETIME
FROM (SELECT *
     FROM ANIMAL_INS
     ORDER BY DATETIME)
WHERE ROWNUM = 1;

-- -- Case 2:
-- SELECT MIN(DATETIME)
-- FROM ANIMAL_INS;

-- MySQL
-- Case 1;
SELECT MIN(DATETIME)
FROM ANIMAL_INS;

-- -- Case 2:
-- SELECT DATETIME
-- FROM ANIMAL_INS
-- ORDER BY DATETIME
-- LIMIT 1;