-- Oracle
SELECT TO_CHAR(DATETIME, 'HH24') HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 19
ORDER BY TO_CHAR(DATETIME, 'HH24');

-- MySQL
SELECT HOUR(DATETIME) as hour, COUNT(HOUR(DATETIME)) as count
FROM ANIMAL_OUTS
GROUP BY hour
HAVING hour BETWEEN 9 AND 19
ORDER BY hour;