-- KB 준비 SQL 연습
WITH RECURSIVE TIME AS (
    SELECT 0 AS h
    UNION ALL
    SELECT h+1 FROM TIME WHERE h < 23)
SELECT h, COUNT(HOUR(DATETIME))
FROM TIME t LEFT JOIN ANIMAL_OUTS o ON t.h = HOUR(o.DATETIME)
GROUP BY h;