-- Oracle
SELECT a.NAME
FROM CITY a, COUNTRY b
WHERE a.COUNTRYCODE = b.CODE AND b.CONTINENT = 'Africa';
-- MySQL
SELECT a.NAME
FROM CITY a LEFT JOIN COUNTRY b
ON a.COUNTRYCODE = b.CODE
WHERE b.CONTINENT = 'Africa';