-- Oracle
SELECT SUM(a.POPULATION)
FROM CITY a, COUNTRY b
WHERE a.COUNTRYCODE = b.CODE AND b.CONTINENT = 'Asia';
-- MySQL
SELECT SUM(a.POPULATION)
FROM CITY a LEFT JOIN COUNTRY b
ON a.COUNTRYCODE = b.CODE
WHERE b.CONTINENT = 'Asia';