-- Oracle
SELECT b.CONTINENT, TRUNC(AVG(a.POPULATION),0)
FROM CITY a, COUNTRY b
WHERE a.COUNTRYCODE = b.CODE
GROUP BY b.CONTINENT;
-- MySQL
SELECT b.CONTINENT, TRUNCATE(AVG(a.POPULATION),0)
FROM CITY a INNER JOIN COUNTRY b
ON a.COUNTRYCODE = b.CODE
GROUP BY b.CONTINENT;